### PR TITLE
adding my name to contributer list

### PR DESCRIPTION
**Pull request by mjlearn13**
Hi, I just added my name to the contributor list. @ericnormand

### CODE REVIEW

**Comment by AvidCoder101** [comment]
@mjlearn13 have you ever contributed here before?

**Comment by AvidCoder101** [comment]
If not, you first need to add a resource and then you can add your name to the contributors list

**Comment by mjlearn13** [comment]
Hi,

Ok, that makes sense.  Will do once I add a resource.

Kind regards,

Mani

**Comment by AvidCoder101** [comment]
Thanks for understanding (:

**Comment by mjlearn13** [comment]
No problem, thank you.

**Pull request closed without merging**
