### PR TITLE
adding two links with description

### PR DESCRIPTION
**Pull request by Memphis1983**
I couldn't find any resources for learning web development so I've made a new `.md` file and added two links to it. I hope this is acceptable if not please let me know. Thanks

### CODE REVIEW

**Comment by AvidCoder101** [comment]
@Memphis1983 There does seem to be a WebDev markdown file that you could add your resources to. If you could do so, I would be happy to merge the PR (:

**Comment by arjunkharbanda** [comment]
@AvidCoder101 Expect more PR then usual all this month because of hacktoberfest

**Comment by AvidCoder101** [comment]
Does this mean that I could merge this?

**Comment by sophiabrandt** [comment]
Sorry, but this pull request did not follow the guidelines in `CONTRIBUTING.md` where we explain how to add resources. If you want to add a new category, follow the steps in step 4.

I'm going to close your pull request for now. Feel free to make a new one that honors the contributing guidelines. Thank you.

**Comment by Memphis1983** [comment]
@AvidCoder101 Yes, but the WebDevTools markdown file contains developer tools but no links to Web Development courses. I checked them out first to see if there were any similar links, but I couldn't find any, so I created a new file, but I see now that I should have opened a new issue for this for approval, as @sophiabrandt suggested.

This issue has now been closed; may I reopen it and await your approval? Please advise, and thank you :)

**Comment by sophiabrandt** [comment]
@Memphis1983 follow the steps in the contributing guidelines, please. I agree with you that it does not make sense to add course to the "web dev tools" page.

The guidelines explain what you need to do: open a new issue to discuss adding new page. If that's aproved, make a new category and add your resources.

You can make a new pull request for that, as this one is closed. Good luck and have fun.

**Comment by Memphis1983** [comment]
Will do that and thank you @sophiabrandt :)

**Comment by arjunkharbanda** [comment]
@AvidCoder101 @sophiabrandt  should we rename MOOCS.md to just free online courses or should create section altogether?

**Pull request closed without merging**
