### PR TITLE
added few resources

### PR DESCRIPTION
**Pull request by ayushi2410**
@ericnormand

### CODE REVIEW

**Review by MattCSmith — CHANGES_REQUESTED** [review]
Please provide a description for the links added.

**Comment by AvidCoder101** [comment]
@ayushi2410 any updates?

**Comment by AvidCoder101** [comment]
@ayushi2410 if you need any help, please don't hesitate to ask 😀

**Comment by ayushi2410** [comment]
@ayushi2410  yes I have added the description.

**Pull request merged**
