### PR TITLE
Jallah's Update

### PR DESCRIPTION
**Pull request by Sumbo-1**
Added my name to the Contributors List

### CODE REVIEW

**Comment by sophiabrandt** [comment]
@Sumbo-1 what resource did you add or what changes did you make? I can't find it. Just out of curiosity.

**Comment by Shubhamai** [comment]
Hi @sophiabrandt He just made changes to `CONTRIBUTORS.md` to add here name and link to her Github profile. You can find the changes he made from [here](https://github.com/zero-to-mastery/resources/pull/425/files)

**Comment by sophiabrandt** [comment]
Hmm, that's not the purpose of _this_ repository. You should only add your name to the `CONTRIBUTORS.md` if you made changes according to the Contributors guide https://github.com/zero-to-mastery/resources/blob/master/CONTRIBUTING.md.
@Sumbo-1 do you plan to make some other changes? Otherwise I plan to revert the commit.

**Comment by ultraflourine** [comment]
@sophiabrandt yes, I.am currently adding and will push the changes soon

**Comment by sophiabrandt** [comment]
I will revert the commit for now.
I feel that we should honor the idea that any work you do on the project entitles you to an entry in the `CONTRIBUTORS.md` file. Thus showing that you participated in providing some value to the community and this repository.

While this project is a playground for the ZTM community, it's also an opportunity to mirror a real codebase. I think we should adhere to the guidelines.

**Pull request merged**
