### PR TITLE
Added Coding Websites.md

### PR DESCRIPTION
**Pull request by aniketsingh98571**
Please review my PR and do suggest if any changes required.
@MattCSmith @sophiabrandt @tonydc1997 @SamirJouni

### CODE REVIEW

**Comment by aniketsingh98571** [comment]
@SamirJouni Please add the "Hacktoberfest" label to your repo and also add "Hacktoberfest-accepted" labels to the merged PR,
as the rules for Hacktoberfest have changed. It's a request to you to please add the "Hacktoberfest-accepted" label to my merged PR.

**Comment by MattCSmith** [comment]
Hey @aniketsingh98571 
The Hacktoberfest label has been added to all relevant ZTM repositories now. 
The `Hacktoberfest-accepted` label is only required if a PR was made to a repo that did not have the `Hacktoberfest` label as of 12 UTC today. 

Feel free to reach out to me on Discord if you have any questions.

**Comment by sophiabrandt** [comment]
@aniketsingh98571 the next time, please follow the Contributing guidelines https://github.com/zero-to-mastery/resources/blob/master/CONTRIBUTING.md.

**Comment by sophiabrandt** [comment]
@aniketsingh98571 I've added the label "invalid" for now. The category you added it confusing and the resources are probably better suited for a different category.
Please feel free to discuss opening a new category as per Contributing guidelines or add your resources to different categories.

**Pull request merged**
