### PR TITLE
Added Game Development Resources

### PR DESCRIPTION
**Pull request by vivekboss99**
Added resources in an organized way with different categories.

### CODE REVIEW

**Comment by vivekboss99** [comment]
Please help me resolve this issue i put in like 3 hours to find resource links and organize them.

**Comment by sophiabrandt** [comment]
@vivekboss99 hey, thanks for sharing. The Contributor's Guide says:
> If you want to create a new category for your resources, kindly open an issue to let the project maintainers know of this new category before creating one.

Can you please do that?

**Comment by vivekboss99** [comment]
@sophiabrandt I actually created a issue , issue number #524

**Comment by sophiabrandt** [comment]
Oh, sorry, I didn't see that 😅. Let's discuss this in the issue and then resolve your pull request together.

**Comment by vivekboss99** [comment]
@sophiabrandt  you merged it but i'm not able to see my changes in the resources and there is still travis CI build error,please guide me for figuring out what's wrong with my changes.

**Comment by vivekboss99** [comment]
@sophiabrandt just out of curiosity why was my commit getting Travis-build error and thanks making the changes and merging it.  :)

**Comment by sophiabrandt** [comment]
One link (gimp) was incorrect. I've fixed it in one of the latest commits.

**Comment by vivekboss99** [comment]
@sophiabrandt Thanks for helping.

**Comment by arjunkharbanda** [comment]
Thanks @sophiabrandt managing this repo October is very intense month due to Hacktoberfest my inbox is going nuts 
P.S. How you figured out it was because of single link?

**Comment by sophiabrandt** [comment]
@arjunkharbanda Travis CI Logs.
Yes, maintaining this repo is voluntary, and I will only do it when I have free time, so we'll see how it goes.

**Pull request merged**
