### PR TITLE
Added - username to contributors.md

### PR DESCRIPTION
**Pull request by pawaspy**

### CODE REVIEW

**Comment by sophiabrandt** [comment]
@pawaspy Please point to the the pull request where you contributed to this repository.

Just adding your contributor's name doesn't constitute as something we can accept to this repo.

So if you have already added a link or contributed otherwise, please comment with a reference. Thank you.

**Comment by pawaspy** [comment]
@sophiabrandt check this links :-
1) https://github.com/zero-to-mastery/file-io/pull/179#event-10800682698
2) https://github.com/zero-to-mastery/Animation-Nation/pull/2117#event-10648225784

**Comment by sophiabrandt** [comment]
@pawaspy Thanks! 🙏

**Comment by sophiabrandt** [comment]
@pawaspy uuuh. Just realized that your contributions were to other repos than this one.

The Contributors.md is only meant for this specific repo.
Feel free to contribute to this one (https://github.com/zero-to-mastery/resources/), and add your name to the `CONTRIBUTORS.md` of this repo.

**Pull request merged**
